apiVersion: v1
kind: Service
metadata:
  name: service-webserver
  labels:
    app: webserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: webserver
  type: NodePort
